# Marker Repo - calculations

## Loading packages

In [1]:
import marker_repo as mr
import calculations as calc

## Settings

In [2]:
# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists/panglao"

## Calculate scores

In [3]:
# Compare all lists with contain the keyword "genes"
calc.compare_marker_lists(REPO_LISTS_PATH, "genes")

                         Info                      Marker     Score
16133    Embryonic stem cells  ZSCAN4D ENSMUSG00000090714  5.181784
4462                Monocytes       IFI30 ENSG00000216490  5.181784
10724        Epithelial cells    CDKL1 ENSMUSG00000020990  5.181784
4471                Monocytes      PYCARD ENSG00000103490  5.181784
4469                Monocytes        CSTA ENSG00000121552  5.181784
...                       ...                         ...       ...
4978           T helper cells       CXCR4 ENSG00000121966  2.291412
12458               Monocytes    CXCR4 ENSMUSG00000045382  2.291412
11921         Dendritic cells    CXCR4 ENSMUSG00000045382  2.291412
12408          Megakaryocytes    CXCR4 ENSMUSG00000045382  2.291412
4517   Natural killer T cells       CXCR4 ENSG00000121966  2.291412

[16134 rows x 3 columns]

In [4]:
# Compare all lists with contain the keyword "mouse"
calc.compare_marker_lists(REPO_LISTS_PATH, "human")

                        Info                  Marker     Score
4025     Gamma delta T cells  TRGV10 ENSG00000211694  5.181784
2192              Adipocytes   CPT1B ENSG00000205560  5.181784
2179              Adipocytes  METRNL ENSG00000176845  5.181784
5587  Hepatic stellate cells  PNPLA3 ENSG00000100344  5.181784
2182              Adipocytes   SYAP1 ENSG00000169895  5.181784
...                      ...                     ...       ...
4390               Monocytes   CXCR4 ENSG00000121966  2.291412
3860         Dendritic cells   CXCR4 ENSG00000121966  2.291412
4193              Mast cells   CXCR4 ENSG00000121966  2.291412
4517  Natural killer T cells   CXCR4 ENSG00000121966  2.291412
7219         Satellite cells   CXCR4 ENSG00000121966  2.291412

[8050 rows x 3 columns]

In [5]:
# Compare all lists with contain the keyword "mouse"
calc.compare_marker_lists(REPO_LISTS_PATH, "mouse")

                         Info                      Marker     Score
8083     Embryonic stem cells  ZSCAN4D ENSMUSG00000090714  5.181784
6995             Luteal cells    PGAM1 ENSMUSG00000011752  5.181784
7021  Peritubular myoid cells   TMEM98 ENSMUSG00000035413  5.181784
7020  Peritubular myoid cells    MYLIP ENSMUSG00000038175  5.181784
3229           Foveolar cells  SPRR2A3 ENSMUSG00000074445  5.181784
...                       ...                         ...       ...
7592               Thymocytes    CXCR4 ENSMUSG00000045382  2.291412
3525           Cardiomyocytes    CXCR4 ENSMUSG00000045382  2.291412
4717             Plasma cells    CXCR4 ENSMUSG00000045382  2.291412
4408                Monocytes    CXCR4 ENSMUSG00000045382  2.291412
3871          Dendritic cells    CXCR4 ENSMUSG00000045382  2.291412

[8084 rows x 3 columns]