# Marker Repo

## Loading packages

In [1]:
import marker_gene_repo as mgr

In [2]:
%load_ext autoreload
%autoreload 2

## Adding a list

### Settings

In [3]:
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/marker_repo/lists"

# The path were the list of marker genes or regions is located
LIST_PATH = "/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood"

# The path were the corresponding metadata file is located
# None, if you like to add the metadata manually
METADATA_PATH = None

### Add metadata

In [4]:
if not METADATA_PATH:
    title = "panglao"
    list_type = "celltype" # celltype, cellcycle, mito, gender, blacklist, ...
    year = "2020"
    tissue = "blood"
    organism = "human"
    kind = "genes" # Genes or Regions
    misc = None
    
metadata = {"Kind": kind, "Organism": organism, "Tissue": tissue, 
             "Year": year, "List type": list_type, "Title": title}

### Checking

In [5]:
# Checking input files and format of list
mgr.check_input_files(LIST_PATH, METADATA_PATH, list_type)

/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood exists.
The format of the list seems correct.

### Prepare folders and add the list

In [7]:
mgr.addList(REPO_LISTS_PATH, LIST_PATH, metadata)

Copied list to /mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood/2020/celltype.

## Search Marker Repo

In [8]:
# Keywords
title = None
list_type = "celltype" # celltype, cellcycle, mito, gender, blacklist, ...
year = None
tissue = "liver"
organism = None
kind = "genes" # Genes or Regions
misc = None

keywords = {"Kind": kind, "Organism": organism, "Tissue": tissue, 
             "Year": year, "List type": list_type, "Title": title}

In [10]:
mgr.searchDB(REPO_LISTS_PATH, keywords)

3 lists have been found:
genes/human/liver/2020/celltype/panglao
genes/human/fetal-liver/2022/celltype/hcm
genes/mouse/liver/2020/celltype/panglao

    Kind Organism       Tissue  Year List type    Title
0  genes    human        liver  2020  celltype  panglao
1  genes    human  fetal-liver  2022  celltype      hcm
2  genes    mouse        liver  2020  celltype  panglao

In [9]:
hits = []
filtered_files = [os.path.join(root, name) for root, dirs, files in os.walk(REPO_LISTS_PATH) for name in files]
all_files = filtered_files

# Filter title
if title:
    filtered_files = [file for file in filtered_files if title in file.split("/")[-1]]
    
# Filter list_type
if list_type:
    filtered_files = [file for file in filtered_files if list_type in file.split("/")[-2]]
    
# Filter year
if year:
    filtered_files = [file for file in filtered_files if year in file.split("/")[-3]]
    
# Filter tissue
if tissue:
    filtered_files = [file for file in filtered_files if tissue in file.split("/")[-4]]
    
# Filter organism
if organism:
    filtered_files = [file for file in filtered_files if organism in file.split("/")[-5]]
    
# Filter kind
if kind:
    filtered_files = [file for file in filtered_files if kind in file.split("/")[-6]]

count = len(filtered_files)
if count > 0:
    print(f"{str(count)} lists have been found:")
else:
    print("Unfortunately there was no hit. Maybe try fewer keywords.")
    
for file in filtered_files:
    hit = file.split("lists/")[1]
    hits.append(hit)
    print(hit)

NameError: name 'os' is not defined

In [78]:
kinds, organisms, tissues, years, ltypes, titles = ([] for i in range(6))
for hit in hits:
    kind, organism, tissue, year, ltype, title = hit.split("/")
    kinds.append(kind)
    organisms.append(organism)
    tissues.append(tissue)
    years.append(year)
    ltypes.append(ltype)
    titles.append(title)
    
list_dict = {"Kind": kinds, "Organism": organisms, "Tissue": tissues, 
             "Year": years, "List type": ltypes, "Title": titles}

df = pd.DataFrame(list_dict)
display(df)

    Kind Organism       Tissue  Year List type    Title
0  genes    human        liver  2020  celltype  panglao
1  genes    human  fetal-liver  2022  celltype      hcm
2  genes    mouse        liver  2020  celltype  panglao

## Combine Lists

## Statistics

In [82]:
all_files

['/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/pancreas/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/connective-tissue/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/brain/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/brain/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/lungs/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/smooth-muscle/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/immune-system/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/epithelium/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/epithelium/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/heart/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/liver/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/adrenal-glands/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gi-tract/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/reproductive/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/kidney/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/zygote/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/vasculature/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/embryo/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/embryo/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/thyroid/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/na/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bone/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bone/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/skin/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/mammary-gland/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/eye/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/eye/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/skeletal-muscle/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/olfactory-system/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/parathyroid-glands/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/oral-cavity/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/thymus/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/placenta/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/urinary-bladder/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/abdomen/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/adipose-tissue/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/adrenal-gland/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/adventitia/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/airway/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/airway-epithelium/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/amniotic-fluid/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/artery/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/arthrosis/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/articularcartilage/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/articulation/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/ascites/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/belly/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bile-duct/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/biliary-tract/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bladder/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood-vessel/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bone-marrow/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/breast/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bronchi/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/bronchus/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/cartilage/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/cavernosum/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/cerebral-organoid/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/cervix/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/colon/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/cornea/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/decidua/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/endocrine-organ/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/endometrium/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/epidermis/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/esophageal/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/esophagus/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/fetal-brain/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/fetal-liver/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/fetal-striatum/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/fetus/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/fundic-gland/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gall-bladder/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gastrointestinal-tract/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/genitals/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/germ/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gingiva/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gonad/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/gut/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/head/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/head-and-neck/2022/celltype/hcm',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/pancreas/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/connective-tissue/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/brain/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/lungs/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/smooth-muscle/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/immune-system/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/epithelium/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/heart/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/liver/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/adrenal-glands/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/gi-tract/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/reproductive/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/kidney/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/zygote/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/vasculature/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/embryo/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/blood/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/thyroid/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/na/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/bone/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/skin/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/mammary-gland/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/eye/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/skeletal-muscle/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/olfactory-system/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/parathyroid-glands/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/oral-cavity/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/thymus/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/placenta/2020/celltype/panglao',
 '/mnt/workspace/mkessle/projects/marker_repo/lists/genes/mouse/urinary-bladder/2020/celltype/panglao']

## Convert lists