# Marker Repo - Search and combine

## Loading packages

In [1]:
import marker_repo as mr

## Settings

In [2]:
# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/marker_repo/lists"

# The path were the list of marker genes or regions is located
LIST_PATH = "/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood"

# The path were the corresponding metadata file is located
# None, if you like to add the metadata manually
METADATA_PATH = None

## Search database

### Load database

In [3]:
df = mr.getDB(REPO_LISTS_PATH)

### Enter keywords

In [4]:
title = None
list_type = "celltype" # celltype, cellcycle, mito, gender, blacklist, ...
year = None
tissue = "blood"
organism = "human"
kind = "genes" # Genes or Regions

# TODO: misc, author, source
misc = None
author = None
source = None

keywords = {"Kind": kind, "Organism": organism, "Tissue": tissue, 
             "Year": year, "List type": list_type, "Title": title}

### Filter lists

In [5]:
filtered_df = mr.searchDB(df, keywords, exact=False)
filtered_df

    Kind Organism        Tissue  Year List type    Title
0  genes    human         blood  2020  celltype  panglao
1  genes    human         blood  2022  celltype      hcm
2  genes    human  blood-vessel  2022  celltype      hcm

### Get and show paths

In [6]:
paths = mr.getPaths(REPO_LISTS_PATH, filtered_df)

/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood/2020/celltype/panglao
/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood/2022/celltype/hcm
/mnt/workspace/mkessle/projects/marker_repo/lists/genes/human/blood-vessel/2022/celltype/hcm

## Combine Lists using search results

In [7]:
combined_df = mr.combineLists(paths, keywords["List type"], file_name="combined_list")

              Cell type   Marker
0         Erythroblasts      CGA
1         Erythroblasts     GPHa
2         Erythroblasts    GPHA1
3         Erythroblasts     FSHA
4         Erythroblasts      LHA
...                 ...      ...
17280  Endothelial cell     CD31
17281  Endothelial cell    LYVE1
17282  Endothelial cell   LYVE-1
17283  Endothelial cell      NaN
17284  Endothelial cell  SMActin

[17285 rows x 2 columns]

Combined list saved: /mnt/workspace/mkessle/projects/annotate_by_marker_and_features/combined_list