# Marker Repo - search and combine lists

## Loading packages

In [1]:
import marker_repo as mr

## Setting

In [2]:
# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists"

## Get and show database

In [3]:
db = mr.get_db(REPO_LISTS_PATH)
display(db)

,list_name,organism_organism_name,organism_taxonomy_id,marker_type,submitter_name,submitter_email,date,source,tags_genotype,tags_gender,tags_life_stage,tags_injury,tags_tissue,tags_treatment
id,,,,,,,,,,,,,,
1,Panglao_Blood,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,WT,mixed,adult,injury_status: non-injured,NaN,NaN
2,Panglao_Heart,mouse,10090,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,WT,male,young adult,injury_status: non-injured,heart,NaN
3,HCM_Stomach,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,06.01.2023,bio-bigdata.hrbmu.edu.cn/CellMarker,WT,mixed,adult,injury_status: non-injured,stomach,NaN
4,HCM_Brain,human,9606,Genes,"Jackson, Peter",peter@jackson.com,06.01.2023,bio-bigdata.hrbmu.edu.cn/CellMarker,Mut,female,embryo,injury_status: injured\ninjury_type: sham,brain,NaN
5,Panglao_Liver,human,9606,Genes,"Lynch, David",twin@peaks.com,08.04.1990,panglao.se,Mut,mixed,elder,NaN,liver,treatment_status: not treated
6,Human_Gender_Genes,human,9606,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN
7,Mouse_Cellcycle,mouse,10090,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,NaN,NaN,NaN,NaN,NaN
8,Zebrafish_Mito_Genes,zebrafish,7955,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN
9,Zebrafish_Cellcycle,zebrafish,7955,Genes,"Kessler, Micha Frederick",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Search database

Enter dictionary with key: column and value: keyword or enter a string to search the whole database:<br>
keywords = {"list_name": "Heart"} -> take only the column "list_name" into account<br>
keywords = {"submitter_name": "Kessler", "tags_gender": "mixed"}  -> take only the columns "submitter_name" and "gender" into account<br>
keywords = "WT" -> take all columns into account<br>

### Examples

In [4]:
keywords = {"list_name": "Heart"}
mr.search_db(db, keywords, case_sensitive=False, exact=False)

,list_name,organism_organism_name,organism_taxonomy_id,marker_type,submitter_name,submitter_email,date,source,tags_genotype,tags_gender,tags_life_stage,tags_injury,tags_tissue,tags_treatment
id,,,,,,,,,,,,,,
2,panglao_heart,mouse,10090,genes,"kessler, micha frederick",micha-frederick.kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,wt,male,young adult,injury_status: non-injured,heart,NaN

In [5]:
keywords = {"submitter_name": "Kessler", "tags_gender": "mixed"} 
mr.search_db(db, keywords, case_sensitive=True, exact=False)

,list_name,organism_organism_name,organism_taxonomy_id,marker_type,submitter_name,submitter_email,date,source,tags_genotype,tags_gender,tags_life_stage,tags_injury,tags_tissue,tags_treatment
id,,,,,,,,,,,,,,
1,Panglao_Blood,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,WT,mixed,adult,injury_status: non-injured,NaN,NaN
3,HCM_Stomach,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,06.01.2023,bio-bigdata.hrbmu.edu.cn/CellMarker,WT,mixed,adult,injury_status: non-injured,stomach,NaN
6,Human_Gender_Genes,human,9606,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN
8,Zebrafish_Mito_Genes,zebrafish,7955,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN

In [6]:
keywords = "WT"
mr.search_db(db, keywords, case_sensitive=True, exact=True)

,list_name,organism_organism_name,organism_taxonomy_id,marker_type,submitter_name,submitter_email,date,source,tags_genotype,tags_gender,tags_life_stage,tags_injury,tags_tissue,tags_treatment
id,,,,,,,,,,,,,,
1,Panglao_Blood,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,WT,mixed,adult,injury_status: non-injured,NaN,NaN
2,Panglao_Heart,mouse,10090,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,27.03.2020,panglao.se,WT,male,young adult,injury_status: non-injured,heart,NaN
3,HCM_Stomach,human,9606,Genes,"Kessler, Micha Frederick",Micha-Frederick.Kessler@mpi-bn.mpg.de,06.01.2023,bio-bigdata.hrbmu.edu.cn/CellMarker,WT,mixed,adult,injury_status: non-injured,stomach,NaN
6,Human_Gender_Genes,human,9606,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN
7,Mouse_Cellcycle,mouse,10090,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,NaN,NaN,NaN,NaN,NaN
8,Zebrafish_Mito_Genes,zebrafish,7955,Genes,"Kessler, Micha Frederick",NaN,NaN,gitlab.gwdg.de/loosolab/software/sc_framework/...,WT,mixed,NaN,NaN,NaN,NaN

## Combine lists

Example 1: Combine all lists which contain the keyword "mixed".

In [7]:
# Save search results in "df"
keywords = "Genes"
df = mr.search_db(db, keywords, case_sensitive=False, exact=True)

# Get UIDs and combine lists
uids = [int(idx) for idx in df.index]
combined_df = mr.combine_lists(REPO_LISTS_PATH, uids)
display(combined_df)

# Drop duplicates (redundant if you want to submit the new list using the submit_lists notebook)
markers_filtered = combined_df.drop_duplicates()
display(markers_filtered)

# Export marker list
mr.export_marker_list(REPO_LISTS_PATH, "Mixed", combined_df)

                             Marker           Info
0               CGA ENSG00000135346  Erythroblasts
1              TFRC ENSG00000072274  Erythroblasts
2              CDH1 ENSG00000039068  Erythroblasts
3               WRN ENSG00000165392  Erythroblasts
4              CD44 ENSG00000026508  Erythroblasts
...                             ...            ...
5967       NDC80 ENSDARG00000071694      g2m_genes
5968       CCNB2 ENSDARG00000036180      g2m_genes
5969  ZGC:153426 ENSDARG00000104436      g2m_genes
5970       KIF23 ENSDARG00000014943      g2m_genes
5971        CTCF ENSDARG00000056621      g2m_genes

[5972 rows x 2 columns]

                             Marker           Info
0               CGA ENSG00000135346  Erythroblasts
1              TFRC ENSG00000072274  Erythroblasts
2              CDH1 ENSG00000039068  Erythroblasts
3               WRN ENSG00000165392  Erythroblasts
4              CD44 ENSG00000026508  Erythroblasts
...                             ...            ...
5967       NDC80 ENSDARG00000071694      g2m_genes
5968       CCNB2 ENSDARG00000036180      g2m_genes
5969  ZGC:153426 ENSDARG00000104436      g2m_genes
5970       KIF23 ENSDARG00000014943      g2m_genes
5971        CTCF ENSDARG00000056621      g2m_genes

[5965 rows x 2 columns]

Combined list saved: /mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists/Mixed