# Marker Repo - submit lists

## Loading packages

In [1]:
import marker_repo as mr
import src.generate_metafile as gm
import src.validate_yaml as validate
import src.utils as utils

## Settings

In [2]:
ORGANISM = "human"
MARKER_TYPE = "genes" # genes or regions

# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists"

# The path of the list to be added to the marker repo.
LIST_PATH = "/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood"

# The path were the corresponding metadata file is located
# None, if you like to add the metadata manually
METADATA_PATH = None

## Get whitelists

In [3]:
mr.getWhitelists()

Fetching whitelists...

Done!

Read genes in order to filter and extend marker genes

In [4]:
if MARKER_TYPE == "genes":
    gene_dict = {}
    w_markers = utils.read_whitelist(f"genes/{ORGANISM}")['whitelist']
    for marker in w_markers:
        name, ensg = marker.split(" ")
        gene_dict[name] = ensg
        gene_dict[ensg] = name

## Read, filter and transform marker list

Read marker list

In [5]:
markers = mr.getList(LIST_PATH, "celltype")
display(markers)

         Cell type   Marker
0    Erythroblasts      CGA
1    Erythroblasts     GPHa
2    Erythroblasts    GPHA1
3    Erythroblasts     FSHA
4    Erythroblasts      LHA
..             ...      ...
880  Reticulocytes    CD49d
881  Reticulocytes    CD49D
882  Reticulocytes  SLC11A2
883  Reticulocytes     DCT1
884  Reticulocytes   NRAMP2

[885 rows x 2 columns]

Filter marker list

In [6]:
if MARKER_TYPE == "genes":
    
     #   w_markers = [gene.split()[0] for gene in w_markers]
    markers_filtered = markers[markers['Marker'].isin(gene_dict.keys())]
    display(markers_filtered)

         Cell type   Marker
0    Erythroblasts      CGA
6    Erythroblasts     TFRC
10   Erythroblasts     CDH1
14   Erythroblasts      WRN
17   Erythroblasts     CD44
..             ...      ...
870  Reticulocytes    FOLR1
872  Reticulocytes    UBE2O
874  Reticulocytes     CD36
879  Reticulocytes    ITGA4
882  Reticulocytes  SLC11A2

[236 rows x 2 columns]

Extend marker list

In [7]:
markers_extended = mr.update_markers(markers_filtered, gene_dict)
display(markers_extended)

/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/marker_repo.py:382: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Marker'] = df['Marker'].apply(apply_update)

         Cell type                   Marker
0    Erythroblasts      CGA ENSG00000135346
6    Erythroblasts     TFRC ENSG00000072274
10   Erythroblasts     CDH1 ENSG00000039068
14   Erythroblasts      WRN ENSG00000165392
17   Erythroblasts     CD44 ENSG00000026508
..             ...                      ...
870  Reticulocytes    FOLR1 ENSG00000110195
872  Reticulocytes    UBE2O ENSG00000175931
874  Reticulocytes     CD36 ENSG00000135218
879  Reticulocytes    ITGA4 ENSG00000115232
882  Reticulocytes  SLC11A2 ENSG00000110911

[236 rows x 2 columns]

Convert marker list in order to append it to the yaml file

In [8]:
marker_dict = mr.dataframe_to_dict(markers_extended, info_col=0, marker_col=1)
marker_list = []
for name in marker_dict.keys():
    marker_list.append({'name': name, 'markers': marker_dict[name]})

## Add metadata

In [9]:
gm.generate_file(REPO_LISTS_PATH, 1, False, marker_list)

The metadata file for ID 1 already exists.

Do you want to overwrite the file?
1:  True
2:  False

KeyboardInterrupt: Interrupted by user

## Validation

In [ ]:
# TODO (?) markers are checked bevore adding