# Marker Repo - submit lists

In [1]:
%load_ext autoreload
%autoreload 2

## Loading packages

In [2]:
import marker_repo as mr
import src.generate_metafile as gm
import src.validate_yaml as validate
import src.utils as utils

## Settings

In [3]:
# The path where the lists of the Marker Repo are stored - probable 'REPO_PATH/lists'
REPO_LISTS_PATH = "/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists"

# The path of the list to be added to the marker repo.
LIST_PATH = "/mnt/workspace/mkessle/projects/marker_repo/dbs/panglao_split/panglao_human_Blood"

# The name of the marker  list
LIST_NAME = "Panglao_Blood"

# The path were the corresponding metadata file is located
# None, if you like to add the metadata manually
METADATA_PATH = None

## Get whitelists

Pull whitelist repository and update if necessary.

In [4]:
mr.getWhitelists()

Fetching whitelists...

Done!

Get essential metadata: Organism and marker type

In [5]:
ORGANISM = mr.select("organism")
MARKER_TYPE = mr.select("marker_type")

Select organism
1:	human 9606
2:	mouse 10090
3:	zebrafish 7955
4:	rat 10114
5:	pig 9823
6:	medaka 8090
7:	chicken 9031
8:	drosophila 7215
9:	yeast 4932
1
Selection: human 9606

Select marker_type
1:	Genes
2:	Genomic regions
1
Selection: Genes

Read genes whitelist in order to filter and extend marker genes

In [6]:
if MARKER_TYPE == "Genes":
    gene_dict = mr.get_gene_dict(ORGANISM)

## Read, filter, extend and transform marker list

Read marker list

In [7]:
markers = mr.getList(LIST_PATH, info_col=0, marker_col=1)
markers['Marker'] = markers['Marker'].str.upper()
display(markers)

              Info   Marker
0    Erythroblasts      CGA
1    Erythroblasts     GPHA
2    Erythroblasts    GPHA1
3    Erythroblasts     FSHA
4    Erythroblasts      LHA
..             ...      ...
880  Reticulocytes    CD49D
881  Reticulocytes    CD49D
882  Reticulocytes  SLC11A2
883  Reticulocytes     DCT1
884  Reticulocytes   NRAMP2

[885 rows x 2 columns]

Filter marker list

In [8]:
# TODO - select filter: keep protein conding only? keep noncoding? keep ... ?
if MARKER_TYPE == "Genes":
    markers_filtered = markers[markers['Marker'].isin(gene_dict.keys())]
    display(markers_filtered)
    markers_filtered = markers_filtered.drop_duplicates()
    display(markers_filtered)

              Info   Marker
0    Erythroblasts      CGA
6    Erythroblasts     TFRC
10   Erythroblasts     CDH1
14   Erythroblasts      WRN
17   Erythroblasts     CD44
..             ...      ...
870  Reticulocytes    FOLR1
872  Reticulocytes    UBE2O
874  Reticulocytes     CD36
879  Reticulocytes    ITGA4
882  Reticulocytes  SLC11A2

[236 rows x 2 columns]

              Info   Marker
0    Erythroblasts      CGA
6    Erythroblasts     TFRC
10   Erythroblasts     CDH1
14   Erythroblasts      WRN
17   Erythroblasts     CD44
..             ...      ...
870  Reticulocytes    FOLR1
872  Reticulocytes    UBE2O
874  Reticulocytes     CD36
879  Reticulocytes    ITGA4
882  Reticulocytes  SLC11A2

[236 rows x 2 columns]

Extend marker list

In [9]:
if MARKER_TYPE == "Genes":
    markers_extended = mr.update_markers(markers_filtered, gene_dict)
    display(markers_extended)

              Info                   Marker
0    Erythroblasts      CGA ENSG00000135346
6    Erythroblasts     TFRC ENSG00000072274
10   Erythroblasts     CDH1 ENSG00000039068
14   Erythroblasts      WRN ENSG00000165392
17   Erythroblasts     CD44 ENSG00000026508
..             ...                      ...
870  Reticulocytes    FOLR1 ENSG00000110195
872  Reticulocytes    UBE2O ENSG00000175931
874  Reticulocytes     CD36 ENSG00000135218
879  Reticulocytes    ITGA4 ENSG00000115232
882  Reticulocytes  SLC11A2 ENSG00000110911

[236 rows x 2 columns]

Convert marker list in order to append it to the yaml file

In [10]:
if MARKER_TYPE == "Genes":
    marker_dict = mr.dataframe_to_dict(markers_extended, info_col=0, marker_col=1)
else:
    # TODO - filter genomic regions?
    marker_dict = mr.dataframe_to_dict(markers, info_col=0, marker_col=1)
    
marker_list = []
for name in marker_dict.keys():
    marker_list.append({'name': name, 'markers': marker_dict[name]})

## Enter metadata

Enter general metadata, tags and add marker list(s) automatically.

In [11]:
# TODO - solve problem of whitelist autocompletion (tissue)
gm.generate_file(REPO_LISTS_PATH, mr.get_UID(REPO_LISTS_PATH), LIST_NAME, False, marker_list, ORGANISM, MARKER_TYPE)

['hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'panglao', 'hcm', 'hcm', 'hcm', 'hcm', 'hcm', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao', 'panglao']
____________________________________________________________________________________________________

                                              Metadata
____________________________________________________________________________________________________

This part contains the metadata of the list.


----------------------------------------------------------------------------------------------------
                                             Submitter
----------------------------------------------------------------------------------------------------

The one who submitted the list to the repository.


The name should be entered in the format 'Last name, First name'.
name: Kessler, Micha Frederick

Do you want to add any of the following optional keys? (1,...,1 or n)
1:  email  The email adress of the submitter.
1

The email adress of the submitter.
email: Micha-Frederick.Kessler@mpi-bn.mpg.de

Do you want to add any of the following optional keys? (1,...,4 or n)
1:  date              The date when the content of the list was
                      published. Format dd.mm.yyyy.
2:  reference_genome  Genome version of markers. WARNING: this key is
                      essential when working with genomic regions!
3:  source            The source of the list.
4:  tags              Tags which describe the list.
1,3,4

The date when the content of the list was published. Format dd.mm.yyyy.
date: 27.03.2020

The source of the list.
source: panglao.se

----------------------------------------------------------------------------------------------------
                                                Tags
----------------------------------------------------------------------------------------------------

Tags which describe the list.


Do you want to add any of the following optional keys? (1,...,8 or n)
1:  genotype
2:  gender
3:  life_stage
4:  ethnicity
5:  tissue
6:  disease
7:  injury
8:  treatment
1,2,3,7
genotype:
1:  Mut
2:  WT
2
gender:
1:  male
2:  female
3:  mixed
3
life_stage:
1:   embryo
2:   infant
3:   child
4:   adolescent
5:   young adult
6:   adult
7:   elder
8:   oocyt
9:   2C
10:  4C
11:  morula
6
injury_status:
1:  non-injured
2:  injured
1

Do you want to add any of the following optional keys? (1,...,1 or n)
1:  injury_type
n

Do you want to add another injury?
1:  True
2:  False
2
----------------------------------------------------------------------------------------------------
                                              SUMMARY
----------------------------------------------------------------------------------------------------


    id: 1
    list_name: Panglao_Blood
    organism:
        organism_name: human
        taxonomy_id: 9606
    marker_type: Genes
    submitter:
        name: Kessler, Micha Frederick
        email: Micha-Frederick.Kessler@mpi-bn.mpg.de
    date: 27.03.2020
    source: panglao.se
    tags:
        genotype: WT
        gender: mixed
        life_stage: adult
        injury:
          - injury_status: non-injured



----------------------------------------------------------------------------------------------------


Is the input correct? You can redo it by selecting 'False'
1:  True
2:  False
1
----------------------------------------------------------------------------------------------------
                                              SUMMARY
----------------------------------------------------------------------------------------------------


  - name: Erythroblasts
    markers:
      - CGA ENSG00000135346
      - TFRC ENSG00000072274
      - CDH1 ENSG00000039068
      - WRN ENSG00000165392
      - CD44 ENSG00000026508
      - KLF1 ENSG00000105610
      - BCL11A ENSG00000119866
      - BPGM ENSG00000172331
      - ETS1 ENSG00000134954
      - EPOR ENSG00000187266
      - IGBP1 ENSG00000089289
      - TFR2 ENSG00000106327
      - GYPA ENSG00000170180
      - LMNB1 ENSG00000113368
      - LRP8 ENSG00000157193
      - GRSF1 ENSG00000132463
      - USE1 ENSG00000053501
      - ITGB1 ENSG00000150093
      - CFP ENSG00000126759
      - ENG ENSG00000106991
      - KIT ENSG00000157404
      - LMO2 ENSG00000135363
      - GATA1 ENSG00000102145
      - TAL1 ENSG00000162367
      - KMT5A ENSG00000183955
      - PIEZO1 ENSG00000103335
  - name: Erythroid-like and erythroid precursor cells
    markers:
      - ALAS2 ENSG00000158578
      - HEXA ENSG00000213614
      - AQP1 ENSG00000240583
      - CCNA2 ENSG00000145386
      - PKLR ENSG00000143627
      - LOX ENSG00000113083
      - ARG1 ENSG00000118520
      - HBB ENSG00000244734
      - HBA1 ENSG00000206172
      - HBA2 ENSG00000188536
      - HBG1 ENSG00000213934
      - HBG2 ENSG00000196565
      - CEACAM1 ENSG00000079385
      - CD36 ENSG00000135218
      - GYPA ENSG00000170180
      - THBS1 ENSG00000137801
      - ITGA4 ENSG00000115232
      - GYPB ENSG00000250361
      - AHSP ENSG00000169877
      - HBM ENSG00000206177
      - FECH ENSG00000066926
      - EPOR ENSG00000187266
      - KIT ENSG00000157404
      - BPGM ENSG00000172331
      - DCAF12 ENSG00000198876
      - HBD ENSG00000223609
      - HEMGN ENSG00000136929
      - HMBS ENSG00000256269
      - NCOA4 ENSG00000266412
      - RBM38 ENSG00000132819
      - UCP2 ENSG00000175567
      - UBB ENSG00000170315
      - TMCC2 ENSG00000133069
      - SLC4A1 ENSG00000004939
      - SLC25A39 ENSG00000013306
      - SLC25A37 ENSG00000147454
      - FOSB ENSG00000125740
      - HTATSF1 ENSG00000102241
      - EPB41 ENSG00000159023
      - RSAD2 ENSG00000134321
      - COX6B2 ENSG00000160471
      - APOA1 ENSG00000118137
      - ASNS ENSG00000070669
      - ALAD ENSG00000148218
      - S100A9 ENSG00000163220
      - MIF ENSG00000240972
      - AHSG ENSG00000145192
      - S100A8 ENSG00000143546
      - ERMAP ENSG00000164010
      - KCNN4 ENSG00000104783
      - IK ENSG00000113141
      - PAN3 ENSG00000152520
      - PFAS ENSG00000178921
      - VAMP5 ENSG00000168899
      - PNPO ENSG00000108439
      - TSPO2 ENSG00000112212
      - RHD ENSG00000187010
      - KLF1 ENSG00000105610
      - TSPAN33 ENSG00000158457
      - EPB42 ENSG00000166947
      - CD44 ENSG00000026508
      - CD47 ENSG00000196776
      - CD55 ENSG00000196352
      - EDRF1 ENSG00000107938
      - EPB41L2 ENSG00000079819
      - GYPC ENSG00000136732
      - KEL ENSG00000197993
      - RHAG ENSG00000112077
      - THRB ENSG00000151090
      - UROD ENSG00000126088
      - UROS ENSG00000188690
      - SNCA ENSG00000145335
  - name: Platelets
    markers:
      - CCL5 ENSG00000271503
      - VEGFA ENSG00000112715
      - PECAM1 ENSG00000261371
      - FCGR2A ENSG00000143226
      - CD36 ENSG00000135218
      - ITGA2B ENSG00000005961
      - GP1BA ENSG00000185245
      - SPN ENSG00000197471
      - CD46 ENSG00000117335
      - ITGA2 ENSG00000164171
      - ITGB3 ENSG00000259207
      - SELP ENSG00000174175
      - CD69 ENSG00000110848
      - CD84 ENSG00000066294
      - CD109 ENSG00000156535
      - CCR3 ENSG00000183625
      - CD226 ENSG00000150637
      - TNFSF14 ENSG00000125735
      - LRRC32 ENSG00000137507
      - LTBR ENSG00000111321
      - PF4 ENSG00000163737
      - GP5 ENSG00000178732
      - F13A1 ENSG00000124491
      - THBS1 ENSG00000137801
      - ABCC4 ENSG00000125257
      - BIN2 ENSG00000110934
      - FERMT3 ENSG00000149781
      - PTCRA ENSG00000171611
      - TUBB1 ENSG00000101162
      - GP9 ENSG00000169704
      - NCOA4 ENSG00000266412
      - RGS18 ENSG00000150681
      - RGS13 ENSG00000127074
      - PPBP ENSG00000163736
      - DAB2 ENSG00000153071
      - HFE ENSG00000010704
      - HLA-H ENSG00000206341
      - CXCR4 ENSG00000121966
      - CLEC1B ENSG00000165682
      - MPL ENSG00000117400
      - F5 ENSG00000198734
      - TREML1 ENSG00000161911
      - P2RY12 ENSG00000169313
      - PRKAR2B ENSG00000005249
      - STX11 ENSG00000135604
      - MFSD2B ENSG00000205639
      - ALOX12 ENSG00000108839
      - PLEK ENSG00000115956
      - SELPLG ENSG00000110876
      - ADGRE5 ENSG00000123146
      - CD40 ENSG00000101017
      - ERO1A ENSG00000197930
      - CD9 ENSG00000010278
      - F11R ENSG00000158769
      - TLR4 ENSG00000136869
      - CRLF2 ENSG00000205755
      - IL1A ENSG00000115008
      - SCARB1 ENSG00000073060
      - ADAM10 ENSG00000137845
      - CCR1 ENSG00000163823
      - CCR4 ENSG00000183813
      - F2R ENSG00000181104
      - NRGN ENSG00000154146
      - OST4 ENSG00000228474
      - SPARC ENSG00000113140
      - GP1BB ENSG00000203618
      - GPX1 ENSG00000233276
      - CAVIN2 ENSG00000168497
      - PPDPF ENSG00000125534
      - MYL9 ENSG00000101335
      - MAP3K7CL ENSG00000156265
      - PTGS1 ENSG00000095303
      - GNG11 ENSG00000127920
      - GRAP2 ENSG00000100351
      - CTSA ENSG00000064601
      - MPIG6B ENSG00000204420
      - WIPF1 ENSG00000115935
      - ARHGDIB ENSG00000111348
      - CDKN2D ENSG00000129355
      - CA2 ENSG00000104267
      - HLA-A ENSG00000206503
      - PDLIM1 ENSG00000107438
      - PDZK1IP1 ENSG00000162366
      - AGPAT1 ENSG00000204310
      - SMOX ENSG00000088826
      - SMO ENSG00000128602
      - SRGN ENSG00000122862
      - SH3BGRL2 ENSG00000198478
      - ATP2A3 ENSG00000074370
      - ALDH2 ENSG00000111275
      - ALOX5AP ENSG00000132965
      - RAP1B ENSG00000127314
      - FHL1 ENSG00000022267
      - VWF ENSG00000110799
      - LAPTM5 ENSG00000162511
      - RASGRP2 ENSG00000068831
      - SLC2A3 ENSG00000059804
      - ARHGAP10 ENSG00000071205
      - RTL8B ENSG00000212747
      - TREML2 ENSG00000112195
      - MMRN1 ENSG00000138722
      - ILK ENSG00000166333
      - NOD2 ENSG00000167207
      - NOX5 ENSG00000255346
      - SERPINE1 ENSG00000106366
      - MAPK14 ENSG00000112062
      - ABCA3 ENSG00000167972
      - CXCL14 ENSG00000145824
      - ESAM ENSG00000149564
      - PREX1 ENSG00000124126
      - S100A9 ENSG00000163220
      - MIF ENSG00000240972
      - ATP8A1 ENSG00000124406
      - PRKCD ENSG00000163932
      - PTGS2 ENSG00000073756
      - F7 ENSG00000057593
      - SLC26A4 ENSG00000091137
      - PALLD ENSG00000129116
      - SLC17A9 ENSG00000101194
      - IL33 ENSG00000137033
      - SIRT3 ENSG00000142082
      - CYP2U1 ENSG00000155016
      - TLR1 ENSG00000174125
      - TLR6 ENSG00000174130
      - BGLAP ENSG00000242252
      - LGALS8 ENSG00000116977
      - ITGB2 ENSG00000160255
      - CD40LG ENSG00000102245
      - ANGPT1 ENSG00000154188
      - ACKR3 ENSG00000144476
  - name: Reticulocytes
    markers:
      - RUVBL1 ENSG00000175792
      - TFRC ENSG00000072274
      - UCP3 ENSG00000175564
      - FOLR1 ENSG00000110195
      - UBE2O ENSG00000175931
      - CD36 ENSG00000135218
      - ITGA4 ENSG00000115232
      - SLC11A2 ENSG00000110911



----------------------------------------------------------------------------------------------------


Is the input correct? You can redo it by selecting 'False'
1:  True
2:  False

1
----------------------------------------------------------------------------------------------------
                                              SUMMARY
----------------------------------------------------------------------------------------------------


    metadata:
        id: 1
        list_name: Panglao_Blood
        organism:
            organism_name: human
            taxonomy_id: 9606
        marker_type: Genes
        submitter:
            name: Kessler, Micha Frederick
            email: Micha-Frederick.Kessler@mpi-bn.mpg.de
        date: 27.03.2020
        source: panglao.se
        tags:
            genotype: WT
            gender: mixed
            life_stage: adult
            injury:
              - injury_status: non-injured
    marker_list:
      - name: Erythroblasts
        markers:
          - CGA ENSG00000135346
          - TFRC ENSG00000072274
          - CDH1 ENSG00000039068
          - WRN ENSG00000165392
          - CD44 ENSG00000026508
          - KLF1 ENSG00000105610
          - BCL11A ENSG00000119866
          - BPGM ENSG00000172331
          - ETS1 ENSG00000134954
          - EPOR ENSG00000187266
          - IGBP1 ENSG00000089289
          - TFR2 ENSG00000106327
          - GYPA ENSG00000170180
          - LMNB1 ENSG00000113368
          - LRP8 ENSG00000157193
          - GRSF1 ENSG00000132463
          - USE1 ENSG00000053501
          - ITGB1 ENSG00000150093
          - CFP ENSG00000126759
          - ENG ENSG00000106991
          - KIT ENSG00000157404
          - LMO2 ENSG00000135363
          - GATA1 ENSG00000102145
          - TAL1 ENSG00000162367
          - KMT5A ENSG00000183955
          - PIEZO1 ENSG00000103335
      - name: Erythroid-like and erythroid precursor cells
        markers:
          - ALAS2 ENSG00000158578
          - HEXA ENSG00000213614
          - AQP1 ENSG00000240583
          - CCNA2 ENSG00000145386
          - PKLR ENSG00000143627
          - LOX ENSG00000113083
          - ARG1 ENSG00000118520
          - HBB ENSG00000244734
          - HBA1 ENSG00000206172
          - HBA2 ENSG00000188536
          - HBG1 ENSG00000213934
          - HBG2 ENSG00000196565
          - CEACAM1 ENSG00000079385
          - CD36 ENSG00000135218
          - GYPA ENSG00000170180
          - THBS1 ENSG00000137801
          - ITGA4 ENSG00000115232
          - GYPB ENSG00000250361
          - AHSP ENSG00000169877
          - HBM ENSG00000206177
          - FECH ENSG00000066926
          - EPOR ENSG00000187266
          - KIT ENSG00000157404
          - BPGM ENSG00000172331
          - DCAF12 ENSG00000198876
          - HBD ENSG00000223609
          - HEMGN ENSG00000136929
          - HMBS ENSG00000256269
          - NCOA4 ENSG00000266412
          - RBM38 ENSG00000132819
          - UCP2 ENSG00000175567
          - UBB ENSG00000170315
          - TMCC2 ENSG00000133069
          - SLC4A1 ENSG00000004939
          - SLC25A39 ENSG00000013306
          - SLC25A37 ENSG00000147454
          - FOSB ENSG00000125740
          - HTATSF1 ENSG00000102241
          - EPB41 ENSG00000159023
          - RSAD2 ENSG00000134321
          - COX6B2 ENSG00000160471
          - APOA1 ENSG00000118137
          - ASNS ENSG00000070669
          - ALAD ENSG00000148218
          - S100A9 ENSG00000163220
          - MIF ENSG00000240972
          - AHSG ENSG00000145192
          - S100A8 ENSG00000143546
          - ERMAP ENSG00000164010
          - KCNN4 ENSG00000104783
          - IK ENSG00000113141
          - PAN3 ENSG00000152520
          - PFAS ENSG00000178921
          - VAMP5 ENSG00000168899
          - PNPO ENSG00000108439
          - TSPO2 ENSG00000112212
          - RHD ENSG00000187010
          - KLF1 ENSG00000105610
          - TSPAN33 ENSG00000158457
          - EPB42 ENSG00000166947
          - CD44 ENSG00000026508
          - CD47 ENSG00000196776
          - CD55 ENSG00000196352
          - EDRF1 ENSG00000107938
          - EPB41L2 ENSG00000079819
          - GYPC ENSG00000136732
          - KEL ENSG00000197993
          - RHAG ENSG00000112077
          - THRB ENSG00000151090
          - UROD ENSG00000126088
          - UROS ENSG00000188690
          - SNCA ENSG00000145335
      - name: Platelets
        markers:
          - CCL5 ENSG00000271503
          - VEGFA ENSG00000112715
          - PECAM1 ENSG00000261371
          - FCGR2A ENSG00000143226
          - CD36 ENSG00000135218
          - ITGA2B ENSG00000005961
          - GP1BA ENSG00000185245
          - SPN ENSG00000197471
          - CD46 ENSG00000117335
          - ITGA2 ENSG00000164171
          - ITGB3 ENSG00000259207
          - SELP ENSG00000174175
          - CD69 ENSG00000110848
          - CD84 ENSG00000066294
          - CD109 ENSG00000156535
          - CCR3 ENSG00000183625
          - CD226 ENSG00000150637
          - TNFSF14 ENSG00000125735
          - LRRC32 ENSG00000137507
          - LTBR ENSG00000111321
          - PF4 ENSG00000163737
          - GP5 ENSG00000178732
          - F13A1 ENSG00000124491
          - THBS1 ENSG00000137801
          - ABCC4 ENSG00000125257
          - BIN2 ENSG00000110934
          - FERMT3 ENSG00000149781
          - PTCRA ENSG00000171611
          - TUBB1 ENSG00000101162
          - GP9 ENSG00000169704
          - NCOA4 ENSG00000266412
          - RGS18 ENSG00000150681
          - RGS13 ENSG00000127074
          - PPBP ENSG00000163736
          - DAB2 ENSG00000153071
          - HFE ENSG00000010704
          - HLA-H ENSG00000206341
          - CXCR4 ENSG00000121966
          - CLEC1B ENSG00000165682
          - MPL ENSG00000117400
          - F5 ENSG00000198734
          - TREML1 ENSG00000161911
          - P2RY12 ENSG00000169313
          - PRKAR2B ENSG00000005249
          - STX11 ENSG00000135604
          - MFSD2B ENSG00000205639
          - ALOX12 ENSG00000108839
          - PLEK ENSG00000115956
          - SELPLG ENSG00000110876
          - ADGRE5 ENSG00000123146
          - CD40 ENSG00000101017
          - ERO1A ENSG00000197930
          - CD9 ENSG00000010278
          - F11R ENSG00000158769
          - TLR4 ENSG00000136869
          - CRLF2 ENSG00000205755
          - IL1A ENSG00000115008
          - SCARB1 ENSG00000073060
          - ADAM10 ENSG00000137845
          - CCR1 ENSG00000163823
          - CCR4 ENSG00000183813
          - F2R ENSG00000181104
          - NRGN ENSG00000154146
          - OST4 ENSG00000228474
          - SPARC ENSG00000113140
          - GP1BB ENSG00000203618
          - GPX1 ENSG00000233276
          - CAVIN2 ENSG00000168497
          - PPDPF ENSG00000125534
          - MYL9 ENSG00000101335
          - MAP3K7CL ENSG00000156265
          - PTGS1 ENSG00000095303
          - GNG11 ENSG00000127920
          - GRAP2 ENSG00000100351
          - CTSA ENSG00000064601
          - MPIG6B ENSG00000204420
          - WIPF1 ENSG00000115935
          - ARHGDIB ENSG00000111348
          - CDKN2D ENSG00000129355
          - CA2 ENSG00000104267
          - HLA-A ENSG00000206503
          - PDLIM1 ENSG00000107438
          - PDZK1IP1 ENSG00000162366
          - AGPAT1 ENSG00000204310
          - SMOX ENSG00000088826
          - SMO ENSG00000128602
          - SRGN ENSG00000122862
          - SH3BGRL2 ENSG00000198478
          - ATP2A3 ENSG00000074370
          - ALDH2 ENSG00000111275
          - ALOX5AP ENSG00000132965
          - RAP1B ENSG00000127314
          - FHL1 ENSG00000022267
          - VWF ENSG00000110799
          - LAPTM5 ENSG00000162511
          - RASGRP2 ENSG00000068831
          - SLC2A3 ENSG00000059804
          - ARHGAP10 ENSG00000071205
          - RTL8B ENSG00000212747
          - TREML2 ENSG00000112195
          - MMRN1 ENSG00000138722
          - ILK ENSG00000166333
          - NOD2 ENSG00000167207
          - NOX5 ENSG00000255346
          - SERPINE1 ENSG00000106366
          - MAPK14 ENSG00000112062
          - ABCA3 ENSG00000167972
          - CXCL14 ENSG00000145824
          - ESAM ENSG00000149564
          - PREX1 ENSG00000124126
          - S100A9 ENSG00000163220
          - MIF ENSG00000240972
          - ATP8A1 ENSG00000124406
          - PRKCD ENSG00000163932
          - PTGS2 ENSG00000073756
          - F7 ENSG00000057593
          - SLC26A4 ENSG00000091137
          - PALLD ENSG00000129116
          - SLC17A9 ENSG00000101194
          - IL33 ENSG00000137033
          - SIRT3 ENSG00000142082
          - CYP2U1 ENSG00000155016
          - TLR1 ENSG00000174125
          - TLR6 ENSG00000174130
          - BGLAP ENSG00000242252
          - LGALS8 ENSG00000116977
          - ITGB2 ENSG00000160255
          - CD40LG ENSG00000102245
          - ANGPT1 ENSG00000154188
          - ACKR3 ENSG00000144476
      - name: Reticulocytes
        markers:
          - RUVBL1 ENSG00000175792
          - TFRC ENSG00000072274
          - UCP3 ENSG00000175564
          - FOLR1 ENSG00000110195
          - UBE2O ENSG00000175931
          - CD36 ENSG00000135218
          - ITGA4 ENSG00000115232
          - SLC11A2 ENSG00000110911



----------------------------------------------------------------------------------------------------

Marker list saved:
/mnt/workspace/mkessle/projects/annotate_by_marker_and_features/lists/Panglao_Blood_1.yaml

## Validation

In [12]:
# TODO (?) markers are checked bevore adding
metadata = utils.read_in_yaml("lists/Panglao_Blood_1.yaml")
validate.validate_file(metadata)

(True, [], [], [], [], [], [])